In [69]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

In [64]:
df = pd.read_csv('bayut_listings.csv')
scaler = MinMaxScaler()

df.head()

       Price Property Type  ...        Area                         Location
0  1,650,000         Floor  ...  523 Sq. M.   Al Rayyan, East Riyadh, Riyadh
1  1,249,000         Floor  ...  500 Sq. M.  Al Khaleej, East Riyadh, Riyadh
2    499,000     Apartment  ...  154 Sq. M.                  Al Sakb, Madina
3    499,000     Apartment  ...  154 Sq. M.                  Al Sakb, Madina
4    499,000     Apartment  ...  154 Sq. M.                  Al Sakb, Madina

[5 rows x 6 columns]

In [3]:
df.describe()

          Price Property Type  ...        Area                          Location
count     14060         14060  ...       14060                             14060
unique      709            10  ...         862                               807
top     750,000     Apartment  ...  300 Sq. M.  Al Mahdiyah, West Riyadh, Riyadh
freq        393          7052  ...         293                               930

[4 rows x 6 columns]

In [48]:
df['Property Type'].unique()
df2 = df[~df['Property Type'].str.contains(r'\d')]

df2 = df2[df2['Number Of Bedrooms'].str.contains(r'\d')]

In [49]:
df2['Property Type'].describe()

count         14040
unique            8
top       Apartment
freq           7034
Name: Property Type, dtype: object

In [50]:
df2.describe()

          Price Property Type  ...        Area                          Location
count     14040         14040  ...       14040                             14040
unique      707             8  ...         860                               806
top     750,000     Apartment  ...  300 Sq. M.  Al Mahdiyah, West Riyadh, Riyadh
freq        393          7034  ...         293                               930

[4 rows x 6 columns]

In [51]:
df2['Area'] = df2['Area'].apply(lambda x: x.replace('Sq. M.',''))

In [38]:
df2.describe()

          Price Property Type  ...   Area                          Location
count     14058         14058  ...  14058                             14058
unique      708             8  ...    861                               806
top     750,000     Apartment  ...   300   Al Mahdiyah, West Riyadh, Riyadh
freq        393          7052  ...    293                               930

[4 rows x 6 columns]

In [39]:
df2.head(10)

       Price Property Type  ...    Area                               Location
0  1,650,000         Floor  ...    523          Al Rayyan, East Riyadh, Riyadh
1  1,249,000         Floor  ...    500         Al Khaleej, East Riyadh, Riyadh
2    499,000     Apartment  ...    154                         Al Sakb, Madina
3    499,000     Apartment  ...    154                         Al Sakb, Madina
4    499,000     Apartment  ...    154                         Al Sakb, Madina
5    950,000     Apartment  ...    220          Al Rabwa, North Jeddah, Jeddah
6    560,000     Apartment  ...    134          Al Rabwa, North Jeddah, Jeddah
7    550,000     Apartment  ...    131         Al Marwah, North Jeddah, Jeddah
8    270,000     Apartment  ...  3,200   Al Faisaliyah, Central Jeddah, Jeddah
9    360,000     Apartment  ...  3,200   Al Faisaliyah, Central Jeddah, Jeddah

[10 rows x 6 columns]

In [65]:
df2['Area'] = df2['Area'].apply(lambda x: x.replace(',',''))
df2['Price'] = df2['Price'].apply(lambda x: x.replace(',',''))

In [90]:
df2['Area'] = df2['Area'].apply(lambda x: pd.to_numeric(x))
df2['Area'] = pd.DataFrame(scaler.fit_transform(df2['Area'].to_numpy().reshape(-1,1)))
df2['Price'] = df2['Price'].apply(lambda x: pd.to_numeric(x))
df2['Price'] =pd.DataFrame(scaler.fit_transform(df2['Price'].to_numpy().reshape(-1,1)))

In [98]:
df2.shape

(14040, 6)